# Data Preprocessing
What kind of things?
- NaN, Null (is not allowed)
- string (is not allowed)

## Data Encoding

### Label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', 'refrigerator', 'computer', 'fan', 'fan', 'mixer', 'mixer']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("encoding value:", labels)

encoding value: [0 4 1 2 2 3 3]


In [2]:
print(encoder.classes_)

['TV' 'computer' 'fan' 'mixer' 'refrigerator']


In [3]:
print(encoder.inverse_transform([1, 2, 3, 4, 0, 0, 2]))

['computer' 'fan' 'mixer' 'refrigerator' 'TV' 'TV' 'fan']


### One-Hot Encoding

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', 'refrigerator', 'computer', 'fan', 'fan', 'mixer', 'mixer']

items = np.array(items).reshape(-1, 1)
print(items)

[['TV']
 ['refrigerator']
 ['computer']
 ['fan']
 ['fan']
 ['mixer']
 ['mixer']]


In [6]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
(7, 5)


In [7]:
import pandas as pd

df = pd.DataFrame({'item':['TV', 'refrigerator', 'microwave oven', 'computer', 'fan', 'fan']})

In [8]:
pd.get_dummies(df)

item_TV  item_computer  item_fan  item_microwave oven  item_refrigerator
0        1              0         0                    0                  0
1        0              0         0                    0                  1
2        0              0         0                    1                  0
3        0              1         0                    0                  0
4        0              0         1                    0                  0
5        0              0         1                    0                  0

## Feature Scaling

Standardization: change value to 0~1 Gaussian
Normalizer: make number from min 0 to max 1
    (in Scikit Learn - adjust vector size)


### StandardScaler

In [9]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScalar

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


fit(): dataset min/max set
transform(): use fit to transform data
fit_transform(): can do fit & transform at once

What kind of problems occur when we do re fit() with test data set?

In [12]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

In [14]:
scaler = MinMaxScaler()

# set min/max to 0/10
scaler.fit(train_array)

# transform train_array using MinMaxScaler
train_scaled = scaler.transform(train_array)

print(np.round(train_array.reshape(-1), 2))
print(np.round(train_scaled.reshape(-1), 2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [15]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)
print(np.round(test_array.reshape(-1), 2))
print(np.round(test_scaled.reshape(-1), 2))

[0 1 2 3 4 5]
[0.  0.2 0.4 0.6 0.8 1. ]


so the good way is...

In [16]:
scaler = MinMaxScaler()

# set min/max to 0/10
scaler.fit(train_array)

# transform train_array using MinMaxScaler
train_scaled = scaler.transform(train_array)

print(np.round(train_array.reshape(-1), 2))
print(np.round(train_scaled.reshape(-1), 2))

test_scaled = scaler.transform(test_array)
print(np.round(test_array.reshape(-1), 2))
print(np.round(test_scaled.reshape(-1), 2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0 1 2 3 4 5]
[0.  0.1 0.2 0.3 0.4 0.5]
