# Numpy

## Numpy ndarray 개요

In [8]:
import numpy as np

In [9]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [10]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'
      .format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


## ndarray의 데이터 타입

In [11]:
list_ = [1, 2, 3]
print(type(list_))
array = np.array(list_)
print(type(array))
print(array, array.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [12]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [13]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

array_int2 = array_float.astype("int32")
print(array_int2, array_int2.dtype)

array_float2 = np.array([1.1, 2.1, 3.1])
array_int3 = array_float2.astype("int32")
print(array_int3, array_int3.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성

In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [15]:
zero_array = np.zeros((3, 2), dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## reshape()

In [17]:
array1 = np.arange(10)
print("array1:\n", array1)

array2 = array1.reshape(2, 5)
print("array2:\n", array2)

array3 = array1.reshape(5, 2)
print("array3:\n", array3)

Array1:
 [0 1 2 3 4 5 6 7 8 9]
Array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array1.reshape(7, 2)

ValueError: cannot reshape array of size 10 into shape (7,2)

In [19]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print("array2 shape:", array2.shape)

array3 = array1.reshape(5, -1)
print("array3 shape:", array3.shape)

[0 1 2 3 4 5 6 7 8 9]
Array2 shape: (2, 5)
Array3 shape: (5, 2)


In [20]:
array4 = array1.reshape(-1, 6)

ValueError: cannot reshape array of size 10 into shape (6)

In [24]:
array1 = np.arange(27)
array3d = array1.reshape(3, 3, 3)
print("array3d:\n", array3d.tolist())

array5 = array3d.reshape(-1, 1)
print("array5:\n", array5.tolist())
print("array5 shape:", array5.shape)

array6 = array1.reshape(-1, 1)
print("array6:\n", array6.tolist())
print("array6 shape:", array6.shape)

array3d:
 [[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23], [24], [25], [26]]
array5 shape: (27, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23], [24], [25], [26]]
array6 shape: (27, 1)


In [27]:
my_array1 = np.arange(16)
array4d = my_array1.reshape(2, 2, 2, 2)
print(array4d.tolist())

my_array2 = array4d.reshape(-1, 1)
print(my_array2.tolist())

[[[[0, 1], [2, 3]], [[4, 5], [6, 7]]], [[[8, 9], [10, 11]], [[12, 13], [14, 15]]]]
[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15]]


## numpy indexing

In [28]:
array1 = np.arange(1, 10)
print("array1:", array1)

value = array1[2]
print("value:", value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [30]:
print("array1[-1]:", array1[-1], "array1[-2]:", array1[-2])

array1[-1]: 9 array1[-2]: 8


In [31]:
array1[0] = 100
print(array1)

[100   2   3   4   5   6   7   8   9]


In [33]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print("array2d[0, 0]:", array2d[0, 0])
print("array2d[0, 1]:", array2d[0, 1])
print("array2d[1, 0]:", array2d[1, 0])
print("array2d[2, 2]:", array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0, 0]: 1
array2d[0, 1]: 2
array2d[1, 0]: 4
array2d[2, 2]: 9


In [34]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [35]:
array4 = array1[:3]
array5 = array1[3:]
array6 = array1[:]

print(array4)
print(array5)
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [36]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print("array2d:\n", array2d)

print("array2d[:2, :2]\n", array2d[:2, :2])
print("array2d[1:3, 0:3]\n", array2d[1:3, 0:3])
print("array2d[1:3, :]\n", array2d[1:3, :])
print("array2d[:, :]\n", array2d[:, :])
print("array2d[:2, 1:]\n", array2d[:2, 1:])
print("array2d[:2, 0]\n", array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, :2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [39]:
print(array2d[0])
print(array2d[0, :])
print(array2d[1])
print(array2d[1, :])

[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]


In [40]:
array2d = np.arange(1, 10).reshape(3, 3)

array1 = array2d[[0, 1], 2]
print(array1.tolist())

array2 = array2d[[0, 1], 0:2]
print(array2.tolist())

array3 = array2d[[0, 1]]
print(array3.tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [41]:
array4 = array2d[0, 1]
print(array4.tolist())

2


In [42]:
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [43]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [45]:
boolean_indexes = np.array([False] * 5 + [True] * 4)
print(boolean_indexes)
array3 = array1d[boolean_indexes]
print(array3)

# True 값이 등장하는 위치의 index를 저장, index로 반환하는 방식

[False False False False False  True  True  True  True]
[6 7 8 9]


## sort() argsort()

In [50]:
org_array = np.array([3, 1, 9, 5])
print(org_array)

sort_array1 = np.sort(org_array)
print(sort_array1)

print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]


In [51]:
print(org_array)

sort_array2 = org_array.sort()
print(sort_array2)

print(org_array)

[3 1 9 5]
None
[1 3 5 9]


In [52]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [53]:
array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [55]:
org_array = np.array([3, 5, 2, 4, 7, 6, 8, 1, 9])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[7 2 0 3 1 5 4 6 8]


In [56]:
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[8 6 4 5 1 3 0 2 7]


In [61]:
import numpy as np

name_array = np.array(["A", "B", "C", "D", "E"])
score_array = np.array([78, 95, 84, 98, 88])

score_array_indices = np.argsort(score_array)[::-1]
print(score_array_indices)
print("order:", name_array[score_array_indices])

[3 1 4 2 0]
order: ['D' 'B' 'E' 'C' 'A']


## linear algebra

In [65]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(7, 13).reshape(3, 2)

dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [66]:
print(A)

A = np.transpose(A)
print(A)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
